name: UHC
main: com.leontg77.ultrahardcore.Main
version: 1.9
author: LeonTG77
description: UHC plugin made for ArcitcUHC by LeonTG77
softdepend: [ProtocolLib, Pregenner]

commands:
  arena:
    description: Join the arena.
    aliases: [a, p]
  ban:
    description: Ban a player.
    aliases: [dq]
  banip:
    description: Ban a ip adress.
    aliases: [ipban]
  board:
    description: Toggle the pregame board.
  border:
    description: View or set the border size.
  broadcast:
    description: Broadcast a message to all players online.
    aliases: [bc, bcast]
  butcher:
    description: Kills all hostile mobs.
  config:
    description: Change the game settings.
  chat:
    description: Mute or clear the chat.
    aliases: [c]
  clearinv:
    description: Clear someones inventory.
    aliases: [clear, clearinv, ci]
  clearxp:
    description: Clear someones xp levels.
    aliases: [cxp]
  edit:
    description: Edit the sign you are looking at.
  end:
    description: End the game and reset everything.
  feed:
    description: Feed someone.
  fire:
    description: Start the firework show.
  fly:
    description: Toggle someones fly mode.
  gamemode:
    description: Change your gamemode.
    aliases: [gm]
  giveall:
    description: Give everyone online an item.
  give:
    description: Give a player an item.
  heal:
    description: Heal someone.
  health:
    description: View someones health.
    aliases: [h]
  helpop:
    description: Ask staff for help.
  hof:
    description: View the hall of fame.
  hotbar:
    description: Save your arena hotbar.
  info:
    description: View information on a player.
  invsee:
    description: Opens the targets inventoty.
  kick:
    description: Kick a player.
  list:
    description: Shows a list of online players.
  matchpost:
    description: Get the link of the match post.
    aliases: [post]
  ms:
    description: Check someones ping to the server
    aliases: [ping]
  msg:
    description: Msg a player something secret.
    aliases: [t, tell, whisper, m]
  mute:
    description: Mute a player or the chat.
  near:
    description: Check for nearby players.
  pm:
    description: Team chat command.
    aliases: [tc]
  pmores:
    description: Send your ore count to your team.
    aliases: [sendores]
  pregen:
    description: Pregen a world.
  pvp:
    description: Toggle pvp in a specific world.
  random:
    description: Create random teams.
  rank:
    description: Change someones rank.
  reply:
    description: Reply to your latest msg.
    aliases: [r]
  scenario:
    description: Enable and disable scenarios
    aliases: [scen]
  sethealth:
    description: Set the health of a player.
  setmaxhealth:
    description: Set the max health of a player.
  skull:
    description: Spawn a player head.
  specchat:
    description: Talk in the spectator chat.
    aliases: [sc]
  spectate:
    description: Change your spectator status.
    aliases: [spec]
  setspawn:
    description: Set the lobby spawn point.
  speed:
    description: Change your fly/walk speed
  spread:
    description: Spread all players and freeze them.
  ac:
    description: Talk in StaffChat.
  start:
    description: Start command.
  stats:
    description: View your stats.
  team:
    description: Team command, check usage.
    aliases: [party]
  tempban:
    description: Tempban a player.
    aliases: [tban]
  text:
    description: Spawn a floating text.
  timeleft:
    description: Check the time left.
  timer:
    description: Hotbar timer command.
  tl:
    description: Display your location to your teammates.
    aliases: [sendcoords, pmcoords, teamcoords, teamloc]
  top:
    description: View the top scores for a specific stat.
  tps:
    description: Check the server tps and usage.
    aliases: [lag]
  tp:
    description: Makes you able to teleport as a spectator.
  uhc:
    description: View the game information.
    aliases: [game]
  unban:
    description: Unban a player.
  unbanip:
    description: Unban a ip adress.
    aliases: [ipunban]
  vote:
    description: Start or end a vote.
  whitelist:
    description: Whitelisting command.
    aliases: [wl]
  world:
    description: Create and manage worlds.
    aliases: [w]
# Scenario Commands.
  target:
    description: View your assassins target.
  class:
    description: View your AssaultAndBarrery type.
  listclass:
    description: View who has what AssaultAndBarrery type.
  bp:
    description: Open your backpack.
  btc:
    description: Add or remove someone from the BestBTC list.
  btclist:
    description: View the BestBTC list.
  pve:
    description: Add or remove someone from the BestPvE list.
  pvelist:
    description: View the BestPvE list.
  bigcrack:
    description: Generate the big crack.
  bl:
    description: View the biomeparanoia colors.
  addcaptain:
    description: Add a captain.
  removecaptain:
    description: Remove a captain.
  randomcaptain:
    description: Add a random captain.
  cycle:
    description: Start or stop the choosing.
  choose:
    description: Choose a player.
  chunkapo:
    description: Generate chunk apoclaypse.
  current:
    description: View the current damage type.
  genie:
    description: Genie command, check usage.
  kings:
    description: Manage kings.
  molehelp:
    description: View mole commands.
  mcl:
    description: Send your loc to your mole team.
  mcc:
    description: Chat with your mole team.
  mcp:
    description: View your mole team.
  mt:
    description: Mystery teams command.
  status:
    description: Check the current resistance type.
  genpyro:
    description: Generate Pyrophobia.
  slavereset:
    description: Reset slavemarket.
  slaveowner:
    description: Manage slave owners.
  startbid:
    description: Start a bid on a player.
  bid:
    description: Bid on a player.
  slimecrack:
    description: Generate the SlimyCrack.
  slist:
    description: View what effects people have.
  super:
    description: Add or remove effects.
  void:
    description: Voidscape generator.